version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/d-kuro/restart-object

workflows:
  golang-workflow:
    jobs:
      - lint:
          golangci-lint-version: "1.17.1"
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  lint:
    parameters:
      golangci-lint-version:
        type: string
    executor:
      name: golang
    steps:
      - checkout
      - go_mod_download
      - run:
          name: install golangci-lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>
            # https://github.com/golangci/golangci-lint/issues/250
            sudo mv ./bin/golangci-lint $GOPATH/bin/
      - run:
          name: run golangci-lint
          command: >
            golangci-lint run \
              --tests \
              --enable-all \
              --disable gochecknoglobals \
              --disable gochecknoinits
  test:
    executor:
      name: golang
    steps:
      - checkout
      - go_mod_download
      - run:
          name: run tests
          command: go test -race -v ./...

  release:
    executor:
      name: golang
    steps:
      - checkout
      - go_mod_download
      - run:
          name: run goreleaser
          command: curl -sL https://git.io/goreleaser | bash
